# secret-todo-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-todo-app # <-- NEW NAME for the deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secret-todo-app # <-- NEW LABEL for the selector
  template:
    metadata:
      labels:
        app: secret-todo-app # <-- NEW LABEL for the pods
    spec:
      containers:
      - name: secret-todo-container
        image: psalva/secret-todo-app:latest # <-- Modified image
        ports:
        - containerPort: 3000
        env:
        - name: APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_TITLE
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MY_SECRET